### ISSUE TITLE
Calculate nonce for the test writer in a blockchain test

### ISSUE THREAD

**Issue by qbzzt** [ethereum/retesteth#116]
Blockchain tests can contain multiple transactions. If we decide to add a transaction in the middle, we need to renumber all the nonce values, which is a pain.

It would be nice if when we don't specify a nonce retesteth would just figure it out for us. The initial nonce is already known (from the pre section), and retesteth knows exactly what transactions are being executed and at what order.

**Comment by winsvega** [comment]
hm, that would be a conflict with tests that put txs with wrong nonce to produce a transaction with invalid nonce.

**Comment by qbzzt** [comment]
> perhaps a keyword woul be a solution? like:
> 
> ```
> nonce: "auto"
> ```

I like that solution. It might be less confusing than just omitting the nonce.

**Comment by winsvega** [comment]
check with latest develop branch if its working well

**Comment by qbzzt** [comment]
It didn't work when I did the `docker build` myself, but when I downloaded it from http://retesteth.ethdevops.io/dretesteth.tar it worked great. Thank you.

I should add it to the docs, probably later today.
