### ISSUE TITLE
fork names standart (Homestead, Frontier...)

### ISSUE THREAD

**Issue by winsvega** [ethereum/retesteth#12]
We need a document that would describe which changes were applied with those forks and how to correctly read tests with those fork names and run the transaction on those fork rules. 

Currently we have. "Frontier, Homestead, EIP150, EIP158, Byzantium, Constantinople" in the test files. 
Also we have FrontierToHomesteadAt5 and so on for transition rules.

**Comment by winsvega** [comment]
@axic qoute:

```"Frontier" "Homestead" "EIP150" "EIP158" "Byzantium"```
It would be nice to use the names Frontier, Homestead, TangerineWhistle, SpuriousDragon, Byzantium. See https://github.com/ethereum/EIPs#past-hard-forks

**Comment by Matthalp** [comment]
@winsvega Is there a typo in this title?`s/standart/standard/`?

**Comment by Matthalp** [comment]
+1 on using "TangerineWhistle" and "SpuriousDragon" over "EIP150" and "EIP158", which is technically inaccurate since those test cover more than just those EIPs in some cases. Also EIP158 was never enacted since EIP161.

**Comment by winsvega** [comment]
forks could be defined for each clients individually with retesteth configs: 
https://github.com/ethereum/tests/tree/develop/Retesteth/default
