### ISSUE TITLE
Error: EthGetBlockByTransaction unmarshal error: Transaction convertion error

### ISSUE THREAD

**Issue by grale88** [ethereum/retesteth#125]
I am currently integrating retesteth with an etc client in order to run particular groups of tests. When running ets test from BlockchainTest\ValidBlocks\bcValidBlockTest\SimpleTx.json I get the following error printed out:

`Error: EthGetBlockByTransaction unmarshal error: Transaction convertion error: Error in DataObject: 
 key: '' type: 'object'
 assert: count(_key) _key=v (DataObject::at)
{
    "blockHash" : "0x71964bfcf258be241c04fbd8a83be92ef633c836209cb0746f96bc044c327db7",
    "blockNumber" : "0x1",
    "from" : "0xa94f5374fce5edbc8e2a8697c15331677e6ebf0b",
    "gasLimit" : "0xc350",
    "gasPrice" : "0xa",
    "hash" : "0x8cb8a30c1c8170e33e2317466a982e591e3b55aa02e353e185841bbeac0cf063",
    "data" : "0x",
    "nonce" : "0x0",
    "to" : "0x095e7baea6a6c7c4c2dfeb977efac326af552d87",
    "transactionIndex" : "0x0",
    "value" : "0xa"
} (bcValidBlockTest/SimpleTx_Istanbul, fork: Istanbul, block: 0)
`

Is there something missing in the transaction object? I checked in retesteth src for required json fields and it seems all are there.

**Comment by winsvega** [comment]
missing signature fields

**Comment by grale88** [comment]
@winsvega Thanks for the feedback. I will try to make changes and return with the result.

**Comment by grale88** [comment]
Once signature fields were added particular test passes current execution step. Closing issue
