### ISSUE TITLE
EIP-2718 typed transactions are malformed

### ISSUE THREAD

**Issue by garyschulte** [ethereum/retesteth#126]
Running the ethereum general state tests against Besu, we are getting `Invalid params` responses from our json-rpc endpoint.  Looking at what retesteth is generating for 2930 transactions, the txdata is getting RLP encoded, such that we get: [RLP(01 + RLP(tr))](https://github.com/ethereum/retesteth/blob/master/retesteth/testStructures/types/Ethereum/TransactionAccessList.cpp#L127-L147)
 

The [spec for 2718](https://eips.ethereum.org/EIPS/eip-2718#specification), and what besu is expecting to be the json-rpc format, is simply the opaque bytes 01 + RLP(tr)

for example:
 the first accessList transaction in stEIP2930/addressOpcodes encodes the raw transaction as

```
0xb9010b01f901070180018402625a0094cccccccccccccccccccccccccccccccccccccccc830186a0b8441a8451e600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f85bf859940000000000000000000000000000000000000101f842a00000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000060a701a0afb6e247b1c490e284053c87ab5f6b59e219d51f743f7a4d83e400782bc7e4b9a0479a268e0e0acd4de3f1e28e4fac2a6b32a4195e8dfa9d19147abe8807aa6f64
```

rather than:
```
0x01f901070180018402625a0094cccccccccccccccccccccccccccccccccccccccc830186a0b8441a8451e600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f85bf859940000000000000000000000000000000000000101f842a00000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000060a701a0afb6e247b1c490e284053c87ab5f6b59e219d51f743f7a4d83e400782bc7e4b9a0479a268e0e0acd4de3f1e28e4fac2a6b32a4195e8dfa9d19147abe8807aa6f64
```

After discussing it with the other besu contributors, it was deemed that what retesteth is generating for typed transactions is malformed.  I have taken a preliminary stab at changing this encoding, but it looks like the expectation that raw transactions are explicitly valid RLP encoded bytes is in several places in the codebase.

**Comment by winsvega** [comment]
is this in the argument of an RPC method?

**Comment by SuburbanDad** [comment]
Yes, this is in the context of an RPC method.  Besu is still supporting RPC currently.  If I change the [besu rpc endpoint behavior](https://github.com/hyperledger/besu/pull/2100) to first decode as RLP, then decode the transaction, besu is able to decode and all is well.  So presumably an encoding exception will work.  I started down this path but found a lot of failed validations and decided it would be best to consult with the maintainers first.

What method might we test besu with other than rpc?

**Comment by SuburbanDad** [comment]
Yes, this is in the context of an RPC method.  Besu is still supporting RPC currently.  If I change the [besu rpc endpoint behavior](https://github.com/hyperledger/besu/pull/2100) to first decode as RLP, then decode the transaction, besu is able to decode and all is well.  So presumably an encoding exception will work.  I started down this path but found a lot of failed validations and decided it would be best to consult with the maintainers first.

What method might we test besu with other than rpc?

**Comment by garyschulte** [comment]
Yes, this is in the context of an RPC method.  Besu is still supporting RPC currently.  If I change the [besu rpc endpoint behavior](https://github.com/hyperledger/besu/pull/2100) to first decode as RLP, then decode the transaction, besu is able to decode and all is well.  So presumably an encoding exception will work.  I started down this path but found a lot of failed validations and decided it would be best to consult with the maintainers first.

What method might we test besu with other than rpc?

**Comment by winsvega** [comment]
Other then the RPC we have t8ntool protocol. It is when the client provide a tool that eats transactions and pre state info and outputs the post state information. 

RPC method:
+ native blockchain testing 
- requires client stability as all the tests are run non stop

T8ntool:
- blockchain testing is impossible, but retesteth cover this part as much as it can.
+ more stable and simple.  

since the besu was very unstable with RPC methods since the begining perhaps making a t8ntool approach would be a good idea. As I am getting message from Ori that besu crashed again on RPC.

**Comment by SuburbanDad** [comment]
>typed transactions exported without rlp prefix (as plain 01 + tx.bytes)

these changes look good to me, but the access list transactions are still coming across as:
```
{"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["0xb9010b01f901070180018402625a0094cccccccccccccccccccccccccccccccccccccccc830186a0b8441a8451e600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f85bf859940000000000000000000000000000000000000101f842a00000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000060a701a0afb6e247b1c490e284053c87ab5f6b59e219d51f743f7a4d83e400782bc7e4b9a0479a268e0e0acd4de3f1e28e4fac2a6b32a4195e8dfa9d19147abe8807aa6f64"],"id":3}
```

And on json-rpc, we are expecting:
```
{"jsonrpc":"2.0","method":"eth_sendRawTransaction","params":["0x01f901070180018402625a0094cccccccccccccccccccccccccccccccccccccccc830186a0b8441a8451e600000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000f85bf859940000000000000000000000000000000000000101f842a00000000000000000000000000000000000000000000000000000000000000000a000000000000000000000000000000000000000000000000000000000000060a701a0afb6e247b1c490e284053c87ab5f6b59e219d51f743f7a4d83e400782bc7e4b9a0479a268e0e0acd4de3f1e28e4fac2a6b32a4195e8dfa9d19147abe8807aa6f64"],"id":3}
```

perhaps Transaction. getRawBytes() is getting called rather than the override?

**Comment by winsvega** [comment]
Are you sure you use the build from latest retesteth develop?

**Comment by SuburbanDad** [comment]
I am on current develop branch, and I just re-built after dropping retesteth images and pruning the docker cache.  I got the same behavior on the rpc endpoint.

**Comment by SuburbanDad** [comment]
I think we can close this issue since besu now supports both RLP wrapped typed transactions and the byte prefixed encoding.
https://github.com/hyperledger/besu/pull/2043/files#r608488729

**Comment by winsvega** [comment]
```
I am on current develop branch, and I just re-built after dropping retesteth images and pruning the docker cache. I got the same behavior on the rpc endpoint.
```

something is wrong. please check that you build on latest develop. eth_sendRawTransaction now sends the 01 + tx.bytes
