### ISSUE TITLE
Crash during BlockchainTests execution

### ISSUE THREAD

**Issue by jvdp** [ethereum/retesteth#128]
When running `retesteth -t BlockchainTests` I get the following crash:

```
...
[1;31;49m*** 22 failures are detected in the test module "EthereumTests"
[0;39;49mterminate called after throwing an instance of 'boost::filesystem::filesystem_error'
  what():  boost::filesystem::directory_iterator::construct: No such file or directory: "/var/lib/buildkite-agent/builds/buildkite-i-03206de417802bded-2/input-output-hk/mantis/ets/tests/src/VMTestsFiller"
Finishing retesteth run
```

The exit code is 134.

The mentioned path does indeed not exist, but should it be or is this a bug? This is with [version 8.0.3 of ethereum/tests](https://github.com/ethereum/tests/tree/8.0.3).

**Comment by jvdp** [comment]
@winsvega do you have any idea what could be the problem?

**Comment by winsvega** [comment]
Is it on retesteth develop branch?
The vm tests got removed. Its in tge legacy folder now. And in state tests.

The daily build doesn't show such problem

**Comment by jvdp** [comment]
It is with version `v0.1.0-accesslist_fix` of retesteth, and 8.0.3 of ETS. Is that an incompatible combination?

(It was running `-t BlockchainTests` btw, not anything in the legacy folder.)

**Comment by winsvega** [comment]
the tests are changing it is better to use retesteth/develop to run the recent state change. 
accesslist_fix is for tests 8.0.0

**Comment by winsvega** [comment]
this really is a boost problem. need dynamic test suites and custom test runner. currently too many things are hardcoded by boost
