### ISSUE TITLE
hardcoded home directory

### ISSUE THREAD

**Issue by pirapira** [ethereum/retesteth#15]
When I try to run `retesteth` locally, I see `/home/wins` in an error message.
```
/home/yh/src/retesteth/testeth/RPCSession.cpp(78): fatal error: in "GeneralStateTests/stCallCodes": Error connecting to IPC socket: /home/wins/.ethereum/geth.ipc
```

I think the directory is hardcoded, but it should not, eventually.

**Comment by winsvega** [comment]
yeap, thats work in progress.
