### ISSUE TITLE
Test format suggestion: Make -1 default for data, gas, value

### ISSUE THREAD

**Issue by gumb0** [ethereum/retesteth#158]
Consider allowing to omit `data`, `gas` or `value` in `expect` section, and consider it the same as `-1` by default (expectation for all values)

That would allow to not have ugly things like `gas: !!int -1` in yaml.

**Comment by chfast** [comment]
I'd also like to omit:
- `pre.*.code:`
- `pre.*.balance:`
- `pre.*.nonce:`
- `pre.*.storage:`
- `expected.result`

**Comment by winsvega** [comment]
> I'd also like to omit:
> 
> * `pre.*.code:`
> * `pre.*.balance:`
> * `pre.*.nonce:`
> * `pre.*.storage:`
> * `expected.result`

that whould mean we would need to agree on defalut code,balance,nonce and storage which would be not transparent.
a test without expected result does not check anything upon test generation. however you still can provide empty expect result section

**Comment by winsvega** [comment]
@gumb0 
https://github.com/ethereum/tests/pull/1005

like this?

**Comment by gumb0** [comment]
> @gumb0 [ethereum/tests#1005](https://github.com/ethereum/tests/pull/1005)
> 
> like this?

Yes, looks good.



> that whould mean we would need to agree on defalut code,balance,nonce and storage which would be not transparent.

I would say that all these have natural default values - empty code, empty storage, 0 for balance and nonce.
