### ISSUE TITLE
Transaction tests: support expectations for additionalForks

### ISSUE THREAD

**Issue by gumb0** [ethereum/retesteth#161]
Currently transaction tests are being generated only for forks of the `forks` section of config, but not for those in `additionalForks`.

It would be useful for testing new proposed EIPs to run additional forks, too (perhaps only those that are explicitly mentioned in expectations), because new EIPs are typically tested by defining new forks in additional section.

See example of such tests in https://github.com/ethereum/tests/pull/1012

**Comment by winsvega** [comment]
https://github.com/ethereum/retesteth/pull/157/commits/c1670139c85816c607ff1ecbd2d3a35f934181de
