### ISSUE TITLE
"Tests finished: 0"

### ISSUE THREAD

**Issue by hmijail** [ethereum/retesteth#176]
Every run of retesteth includes a line saying "Tests finished: 0" that seems to be a mistake.

> retesteth -t GeneralStateTests -- --testpath ../retesteth-tests/ --clients t8ntool --testfile ../retesteth-tests/GeneralStateTests/stExample/add11.json --singlenet Berlin --vmtraceraw trace.jsonl --exectimelog --poststate poststate --fullstate
> Running tests using path: ../retesteth-tests/
> Retesteth config path: /Users/mija/.retesteth
> Active client configurations: 't8ntool '
> Running tests for config 'Ethereum GO on StateTool' 2
> **Tests finished: 0**
> customTestSuite time: 0.147324
> 
> *** No errors detected
> 
> *** Execution time stats
> Total Tests:                                      : 1
> Total Time:                                       : 0.147324
> customTestSuite                               time: 0.147324

**Comment by winsvega** [comment]
https://github.com/ethereum/retesteth/pull/174/commits/d462f36cad18b7a4f64aef8510cc2bfb6d386f56
