### ISSUE TITLE
Bad TestSuite causes no errors

### ISSUE THREAD

**Issue by hmijail** [ethereum/retesteth#177]
This command's response looks almost like the test ran successfully, but actually ran 0 tests.
Note that the test suite says BlockchainTest (last S is missing).

```
retesteth -t BlockchainTest -- --testfile ../retesteth-tests/BlockchainTests/GeneralStateTests/stExample/add11.json

*** No errors detected

*** Execution time stats
*** Total Tests Run: 0

Total Time:                                       : 0.000000
```

**Comment by winsvega** [comment]
https://github.com/ethereum/retesteth/pull/174/commits/b7d26b66c7d53cf2ec0d47299d20b0dae576db02
