### ISSUE TITLE
`--filltests` with missing (or an outdated version of) `solc` should shout an error

### ISSUE THREAD

**Issue by meowsbits** [ethereum/retesteth#190]
Currently only a `WARNING: Error getting solc Version` is given when using the `retesteth --filltests` flag.
Since `solc` is a dependency for this command, `retesteth` should refuse to run if an adequate `solc` version is not present.

Note further that I originally used `snap` to install `solc` and the version installed this was was too old, and caused issues of its own:

```
sudo snap install solc
solc v0.5.16 from Ethereum Build Automation (builds-c) installed
```

but a later version installed manually (via reference in the [Dockerfile](https://github.com/ethereum/retesteth/blob/18ce3e4f17d056c8417604198a35ac21b8a6cc22/Dockerfile#L36-L38)) worked OK.

```
./solc-static-linux --version
solc, the solidity compiler commandline interface
Version: 0.8.5+commit.a4f2e591.Linux.g+
```

**Comment by winsvega** [comment]
retesteth actually have no idea what solc version is required. because it is the tests files that define it. so you can actually use the tests with solc version 0.5 and be just fine. 
also if you don't use any solidity at all, filling the test without solc installed is possible.

**Comment by winsvega** [comment]
Print a warning about solidity version: 
https://github.com/ethereum/retesteth/pull/174/commits/0a89b74722ca524df5d86929660e039340607203
