### ISSUE TITLE
Retesteth Usage Guide

### ISSUE THREAD

**Issue by kendricktan** [ethereum/retesteth#195]
I'm trying to test retesteth on an older version of geth (pre t8tooln), but it keeps failing, is there like a setup guide or smthg for that? tried searching the internet and couldn't find anything

**Comment by winsvega** [comment]
https://ethereum-tests.readthedocs.io/en/latest/retesteth-ref.html

This is tricky and the protocol constantly updates. the current way to as client to run a state transition is t8n.
If your version of geth does not support t8n you have to implement it. 

Use --verbosity RPC to see what are the requests on latests geth. 
start.sh asks t8n tool to process input files.

**Comment by winsvega** [comment]
the super old version of geth (pre t8ntool) was running on hack script. it is not supported long time now. 
maybe if you get old release and try to run it with old geth. but why?
