### ISSUE TITLE
Error: ERROR(3): EIP-1559 config but missing 'currentBaseFee' in env section

### ISSUE THREAD

**Issue by chfast** [ethereum/retesteth#196]
```
Error: ERROR(3): EIP-1559 config but missing 'currentBaseFee' in env section
```

although I have `currentBaseFee: 10` set in `env`.

**Comment by winsvega** [comment]
Which version of geth? Commit hash?

**Comment by chfast** [comment]
The latest stable.

**Comment by winsvega** [comment]
Hm. what command do you use and what test? 
All latests tests are running and filling on latest geth no problem.

**Comment by chfast** [comment]
Works with geth master but not with the latest release.
