### ISSUE TITLE
Remove newline, `\n`, whitespace, and comments inside `:raw` fields in YML

### ISSUE THREAD

**Issue by qbzzt** [ethereum/retesteth#198]
When writing EOF code, it will be very useful to be able to write

```
  - |
    :raw 0xEF0001 # comment
            010004  # comment
            02000100030300000000000000305000
```

However, the YML parser turns the newlines into `\n`s.

**Comment by winsvega** [comment]
https://github.com/ethereum/retesteth/pull/194/commits/c59e9a29b93fb2d52e430c3fbf65e34e6785d785
