### ISSUE TITLE
Support the new vmtrace format from geth, even when there are errors.

### ISSUE THREAD

**Issue by qbzzt** [ethereum/retesteth#199]
If `--vmtrace[raw]` is set then validity of trace outputs shouldn't be forced. If there is an error the vmtrace is more useful not less.

Geth used: `https://github.com/lightclient/go-ethereum.git -b eof`

https://github.com/lightclient/go-ethereum/commit/df2388894ca0cf72acb28d66f235c51ce612a404

**Comment by winsvega** [comment]
https://github.com/ethereum/retesteth/pull/194/commits/666904dd5ddd9215ffefcddbebfd8ee8d34cba8b
