### ISSUE TITLE
t8n: Add "sender" to JSON transaction

### ISSUE THREAD

**Issue by chfast** [ethereum/retesteth#203]
Add "sender" field with transaction sender address to JSON transaction format.

**Comment by winsvega** [comment]
https://github.com/ethereum/retesteth/pull/194/commits/2e71f664e4fa4e1abcf41c7e232db301a4574897

**Comment by axic** [comment]
@chfast this can be closed then?

**Comment by chfast** [comment]
@rodiazet does it work?

**Comment by chfast** [comment]
Done.
