### ISSUE TITLE
docs: document difference between testeth and retesteth

### ISSUE THREAD

**Issue by yxliang01** [ethereum/retesteth#47]
From how I see from these documentations, retesteth is meant to be a next-generation testeth. I have spotted main differences so far:
1. Support concurrent execution of tests
2. not coupled with any particular Ethereum protocol implementation
3. worse performance(when using aleth client and one worker only) due to the need to start a node and communication is done via IPC (compared to simply calling a function in C++)
4. Not all tests supported yet. (TransactionTests / VMTests / RLPTests / BlockchainTests filling)
5. EVM trace rpc methods not specified yet

I think it would be great if the core developers can complete this list and document it somewhere as this is going to be useful for new users to understand.

Thanks

**Comment by yxliang01** [comment]
CC: @winsvega

**Comment by winsvega** [comment]
https://github.com/ethereum/retesteth/wiki

**Comment by winsvega** [comment]
testeth from aleth is not supported father. retesteth has all the same feautures, but depends on a client provider for evm computations.
