### ISSUE TITLE
Documentation improvement: log verbosities clarification

### ISSUE THREAD

**Issue by gumb0** [ethereum/retesteth#58]
From help output:
```
--verbosity <level>           Set logs verbosity. 0 - silent, 1 - only errors, 2 - informative, >2 - detailed
```

The output with values 1, 2, 3, 4 looks the same to me (the command I used was `retesteth/retesteth -t GeneralStateTests/stPreCompiledContracts -- --clients alethIPCDebug --singletest modexp_37120_37111_97_1000000 --verbosity 4`)

It would be nice to better specify which verbosities are actually useful (like what is output at 5, what at higher values, what is max)

**Comment by winsvega** [comment]
currently it is not much of an output to classify. basically the more the value - the more the output. 
at 6 I put all rpc call outputs 
at lessier I put some notes. like indication that a transaction was run, or name of the test that was run.

**Comment by gumb0** [comment]
The help output currently mentions only 0, 1 and 2. You could at least mention what is maximum.

**Comment by winsvega** [comment]
it includes >2

**Comment by winsvega** [comment]
I think the better way is to make verbosity channels. it really makes more sense. because sometimes I need only the RPC logs. or debug logs, but not RPC. or RPC but not the content of RPC. otherwise spending time reading a huge wall of logs looking for what is needed

**Comment by winsvega** [comment]
implemented --verbosity <channel>  version of this
