### ISSUE TITLE
string eth_sendRawTransaction(string _trRLPWithSig)

### ISSUE THREAD

**Issue by winsvega** [ethereum/retesteth#6]
**string eth_sendRawTransaction(string _transactionRLP)**

Accepts a transaction RLP list of the following items: 
```
u256 nonce;
u256 gasPrice;
u256 gasLimit;
hash32 toAddress (could be empty)
u256 value
bytes data;
byte v  (in form 27 + (0|1)  and so on)
h256 r 
h256 s
```
and apply on top of the current chain configuration. (add it to a block which is yet not finalized)
returns the hash of the imported transaction if transaction is valid. or 0 if it's not.

**Comment by winsvega** [comment]
rename to `test_signAndSendTransaction` by proposal of @gumb0

**Comment by pirapira** [comment]
`test_signAndAppendTransaction`?

**Comment by chfast** [comment]
`secretKey` -> `privateKey`?

**Comment by winsvega** [comment]
test files has this field named "secretKey". that might be confusing.

**Comment by chfast** [comment]
The "secret key" is confusing by itself. Nobody knows what it is except ~5 people.

**Comment by cdetrio** [comment]
Why not sign the tx in the test runner and then send it to the client with `eth_sendRawTransaction`? Fewer RPC methods makes it easier to support more clients.

**Comment by winsvega** [comment]
that would require test runner to implement crypto libs.

**Comment by pirapira** [comment]
@winsvega why?  There is `signTransaction` RPC method.

**Comment by winsvega** [comment]
ok. then I should strudy how it works. so maybe there is no need in this method.

**Comment by winsvega** [comment]
@pirapira @cdetrio @holiman
ok. what if instead of adding this new method. there would be a 
test_addAccount(Privatekey)

then it would be possible to use existing signTransaction  and sendRawTransaction

**Comment by winsvega** [comment]
replacing this requirement with standart `eth_sendRawTransaction`

**Comment by winsvega** [comment]
https://github.com/ethereum/retesteth/wiki/RPC-Methods
