### ISSUE TITLE
Documentation improvement: better document client's config files

### ISSUE THREAD

**Issue by gumb0** [ethereum/retesteth#62]
The `config` files and `genesis/<ForkName>.json` files in https://github.com/ethereum/tests/tree/develop/Retesteth are not sufficiently documented, I think. There are some portions `config` files mentioned in https://github.com/ethereum/retesteth/wiki/Add-client-configuration-to-Retesteth but ideally I'd like to see what is the schema of these files, what must be included, what may be optionally included, what is not included, how retesteth uses these files exactly.

For example, currently it seems that these fields are required in `config`:
- `name`
- `socketType`
- `socketAddress`
- `forks`
- `additonalForks` (what is this, how is it different from `forks`?)

And in `*.json`:
- `params`
- `accounts` with a list of precompiles (this actually might be required only for aleth), but no other accounts

This kind of info would be useful in the guide "how to mare retesteth work with your client"

**Comment by winsvega** [comment]
https://github.com/ethereum/retesteth/wiki/Add-client-configuration-to-Retesteth#config-file

**Comment by winsvega** [comment]
https://ethereum-tests.readthedocs.io/en/latest/config-dir.html
