### ISSUE TITLE
Some nitpicky suggestions around socketType and socketAddress

### ISSUE THREAD

**Issue by gumb0** [ethereum/retesteth#64]
1. What retesteth calls "TCP"-type connection (in docs and in cofigs) all clients call more accurately "HTTP":
geth - "HTTP-RPC" https://github.com/ethereum/go-ethereum#programmatically-interfacing-geth-nodes
Besu - "JSON-RPC over HTTP" https://besu.hyperledger.org/en/stable/HowTo/Interact/APIs/API/
Nethermind - "JSON RPC via HTTP" https://nethermind.readthedocs.io/en/latest/jsonrpc.html

2. `socketAddress` could perhaps better be called `endpoint`

3. `endpoint` could include `http://` (maybe at some point you support WebSockets, then `ws://` will be possible)

4. If `endpoint` includes `http://` you don't need `socketType` at all, it can be determined from the path/address itself.

**Comment by winsvega** [comment]
4)  socketType exists for ipc and ipc-debug also. ipc-debug is for devs.

**Comment by gumb0** [comment]
(it's all for devs)
If the difference there is to launch the client process vs connect to a running one, then maybe a separate option like `attach` should control it. But yeah, I see, another option is needed anyway.

**Comment by winsvega** [comment]
here the socketType is more of a retesteth meaning (RPC over TCP client, TOOL client, IPC client...)
configs are slightly changed now.
