### ISSUE TITLE
Test run summary improvement

### ISSUE THREAD

**Issue by gumb0** [ethereum/retesteth#66]
```
> retesteth/retesteth -t GeneralStateTests/stPreCompiledContracts2 -- --clients alethIPCDebug -d 1
...
*** 1 failure is detected in the test module "Master Test Suite"
Finishing retesteth run

--------
*** TOTAL ERRORS DETECTED: 95 errors during all test execution!
```

1. It's confusing to see these contradicting numbers ("1 failure" vs "95 errors"), I guess there is some internal logic to it, I don't know how to better fix it.

2. Also would be nice to see the number of tests that passed or/and total number of tests that were run.

**Comment by winsvega** [comment]
*** 1 failure is detected in the test module "Master Test Suite"   
is fake boost error so to trigger a boost exception. 

I really think boost is a bother at this point. the only thing from boost that is required is 
1) big numbers
2) filesystem 

libdevcore depend on boost and some alg/functions are used in testHelper (I guess replacable)

**Comment by gumb0** [comment]
You could use very light-weight header-only [intx](https://github.com/chfast/intx) for big numbers and `std::filesystem` (with API very similar to boost.filesystem) if you switch to C++17.

**Comment by winsvega** [comment]
https://github.com/ethereum/retesteth/pull/70/commits/e46df678308b85c692fb255a4fbc88bc4cc02778

output of how many tests were run with --exectimelog option
output of which tests failed after TOTAL ERRORS message

**Comment by gumb0** [comment]
> output of how many tests were run with --exectimelog option

why not make it default?

**Comment by winsvega** [comment]
Ah. The total tests run should be by default.
