### ISSUE TITLE
Documentation improvement: list available test suites

### ISSUE THREAD

**Issue by gumb0** [ethereum/retesteth#68]
It would be nice to document what a user can provide to `-t` argument. There are many top-level suites now - `GeneralStateTests`, `BCGeneralStateTests`, `BlockChainTests`, `LegacyTests` It's not obvious at all what is available there, and what kind of tests are in each of these.

Also mentioning `retesteth --list_content` might be useful, though it outputs a lot of stuff I don't understand (unit tests?)

**Comment by winsvega** [comment]
https://github.com/ethereum/retesteth/pull/70/commits/8405dc644c7630904878600cb4b1a9b813114ed6
