### ISSUE TITLE
Feature suggestion: support individual EIP activation

### ISSUE THREAD

**Issue by gumb0** [ethereum/retesteth#69]
This could help with adopting [EIP-centric forking](https://notes.ethereum.org/@holiman/S1ELAYY7S?type=view) process and allowing EIP champions to generate tests from their reference implementation  without it being merged into clients' main line.

The idea is to support the tests format where in place of a fork name you would have a string like `ForkName+XXX` where `ForkName` is one of `Frontier`, `Homestead` etc. and `XXX` is the number of one of the proposed (but not yet accepted) EIPs. See https://github.com/ethereum/tests/commit/8bbbd484227684339ec64ed6a0083d0b137436c8#diff-ee4ed374f5a8e138384eb7782c7b808fR39 for an example of such test.

Currently geth and aleth already support this kind of "fork name" in their testing tools.

For this to work in retesteth you would need clients to also support chain config format that includes these additional EIPs (so that retesteth could send it via `setChainParams`.)
Aleth doesn't yet support this, but it's not difficult to implement when needed, the main challenge is to come up with the exact chain config format for this.

**Comment by winsvega** [comment]
retesteth has nothing to do with this. everything is now configurable. 
you could set up any forkName in the options and assign any chainParams json for this name for any client. and generate the tests with it.

**Comment by winsvega** [comment]
contradicts: https://github.com/ethereum/retesteth/issues/67

**Comment by gumb0** [comment]
Ok I see, makes sense.

Another thing I would find inconvenient for creating the tests for new EIPs is the need to put them into one of the existing suites / test folders. Or otherwise the need to modify the source of retesteth to create a new suite.
(maybe an option to generate tests out of any custom file / folder outside of test folder structure would help with this)

**Comment by winsvega** [comment]
https://github.com/ethereum/retesteth/pull/70/commits/64a9120fb73ede2b472af8e357f1066c21eab139
