### ISSUE TITLE
void test_mineBlocks(int _number)

### ISSUE THREAD

**Issue by winsvega** [ethereum/retesteth#8]
**test_mineBlocks(int _number)**

This method just accept a number and it tells the client to mine a _number blocks on top of the current one.
If there are string test_addTransaction(string _jsonTransaction) methods called in between test_mineBlocks(1) methos, then such transaction must be executed and included into the block. (if valid)

**Comment by winsvega** [comment]
https://github.com/ethereum/retesteth/wiki/RPC-Methods

**Comment by cassa72** [comment]
...

**Comment by tuanggolt** [comment]
open
