### ISSUE TITLE
void test_rewindToBlock(int number)

### ISSUE THREAD

**Issue by winsvega** [ethereum/retesteth#9]
**void test_rewindToBlock(int number)**

This test method should revert the state of the blockchain to a specific block number.
Basically cancelling the blocks so there would be no need to reset the chain genesis if we want to apply different transactions on top of the same genesis block.

**Comment by gumb0** [comment]
Is this needed just for performance optimization?

**Comment by winsvega** [comment]
yes. so not to restart client with new chain params. 
Casey says geth already has `geth has a debug_setHead method, which would be the same as test_rewindToBlock`

**Comment by winsvega** [comment]
https://github.com/ethereum/retesteth/wiki/RPC-Methods
